### Dataset download ###

In [11]:
import sys
import os
import numpy as np
import pandas as pd
import glob
import copy
import tarfile
from pathlib import Path
import cv2
from matplotlib import pyplot as plt
from dotenv import load_dotenv

# Appearance of the Notebook
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Import this module with autoreload
%load_ext autoreload
%autoreload 2

import computervision as cv
from computervision.fileutils import FileOP
from computervision.imageproc import ImageData, is_image
from computervision.imageproc import plot_boxes, enclosing_box, xyxy2xywh, clipxywh, crop_image

from computervision.performance import DetectionMetrics

# Print version info
print(f'Package version: {cv.__version__}')
print(f'Authors:         {cv.__authors__}')
print(f'Python version:  {sys.version}')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Package version: v0.1.0
Authors:         The Core for Computational Biomedicine at Harvard Medical School
https://dbmi.hms.harvard.edu/about-dbmi/core-computational-biomedicine
Python version:  3.12.3 (main, Jun 18 2025, 17:59:45) [GCC 13.3.0]

Full data set: https://universe.roboflow.com/shauns-flow/dental-aq0l2

pre-processed: https://dsets.s3.us-east-1.amazonaws.com/classification_datasets/dataset_dental_roboflow.tar.gz

In [12]:
# Load environmental variables
load_dotenv()
data_root = os.environ.get('DATA_DIR')
if data_root is None:
    print('Edit the "env"file and copy it to the root of the repository.') 
    raise FileNotFoundError('No .env file found. The data directory was not set.')

# Directory to store the data
dataset_name = 'computervision_data'
data_dir = os.path.join(data_root, dataset_name)
example_dir = os.path.join(data_dir, 'examples')

# URL with the data set for manual download
url = os.environ.get('CL_URL')
image_dir_name = os.path.basename(url).split('.')[0]
image_dir = os.path.join(data_dir, image_dir_name, 'cropped')

# Verify the image data on disk
file_list = glob.glob(os.path.join(image_dir, '*.jpg'))
assert len(file_list)==7697, f'Expected 7697 images, found {len(file_list)}.'

### Load the annotation file ###

In [13]:
# Open the annotation file (in the image directory after extraction)
annotations_file_name = 'annotations_cropped.parquet'
annotations_file = os.path.join(image_dir, annotations_file_name)
df = pd.read_parquet(annotations_file)
display(df.head(2))
print(df.shape)

file_col = 'file_name'
bbox_col= 'bbox'
label_col = 'label'

# Chceck the images
file_list = [os.path.join(image_dir, file_name) for file_name in df[file_col].unique()]
checked = [is_image(file) for file in file_list]
assert len(file_list) == sum(checked), f'WARNING: Could not open all {len(file_list)} images at: {image_dir}'
print(f'Image directory:        {image_dir}')
print(f'Total number of images: {len(file_list)}')
print(f'Annotations:            {df.shape[0]}')

,multi_file,file_name,width,height,area,label,bbox,pos,pos_bbox
0,40762886f4.jpg,composite_00_40762886f4.jpg,455,277,126035,composite,"[196, 39, 100, 37]","[20, 19]","[[20, 20, 338, 257], [144, 23, 311, 254]]"
1,40762886f4.jpg,tooth_11_40762886f4.jpg,130,176,22880,tooth,None,[11],None

(7697, 9)
Image directory:        /app/data/computervision_data/dataset_dental_roboflow/cropped
Total number of images: 7697
Annotations:            7697

### Count the annotations ###

In [14]:
n_images = df[[file_col, label_col]].\
    groupby(label_col).\
    nunique().\
    reset_index(drop=False).\
    rename(columns={file_col: 'n_images'}).\
    sort_values(by='n_images', ascending=False).\
    reset_index(drop=True)
display(n_images)

# Select the labels with the minimum number of images for training
min_n_images = 200
min_images_label_list = n_images.loc[n_images['n_images'] >= min_n_images, label_col].tolist()
print(min_images_label_list)
df_filtered = df.loc[df[label_col].isin(min_images_label_list)]
print(df.shape)
print(df_filtered.shape)

                  label  n_images
0                 tooth      3962
1             composite      1486
2               amalgam       660
3              Calculus       627
4                caries       578
5          root filling       237
6                 crown       139
7               implant         7
8  periapical pathology         1

['tooth', 'composite', 'amalgam', 'Calculus', 'caries', 'root filling']
(7697, 9)
(7550, 9)

In [15]:
n_images = df_filtered[[file_col, label_col]].\
    groupby(label_col).\
    nunique().\
    reset_index(drop=False).\
    rename(columns={file_col: 'n_images'}).\
    sort_values(by='n_images', ascending=False).\
    reset_index(drop=True)
display(n_images)

          label  n_images
0         tooth      3962
1     composite      1486
2       amalgam       660
3      Calculus       627
4        caries       578
5  root filling       237

### Function to create the data split by class label ###

In [16]:
def val_test_split(data, label_col=None, n_test_per_class=30, n_val_per_class=30, random_state=123):
    image_numbers = {'test': n_test_per_class,
                     'val': n_val_per_class}
    dset_df = data.copy().sample(frac=1, random_state=random_state). \
        assign(dataset=None).reset_index(drop=True)
    for dataset in image_numbers.keys():
        if label_col is not None:
            labels = dset_df[label_col].unique()
            for label in labels:
                rng = np.random.default_rng(random_state)
                idx_list = rng.choice(dset_df.\
                    loc[(dset_df[label_col] == label) & (dset_df['dataset'].isnull())].\
                    index, size=image_numbers.get(dataset), replace=False)
                dset_df.loc[dset_df.index.isin(idx_list), 'dataset'] = dataset
        else:
            rng = np.random.default_rng(random_state)
            idx_list = rng.choice(dset_df.\
                    loc[dset_df['dataset'].isnull()].\
                    index, size=image_numbers.get(dataset), replace=False)
            dset_df.loc[dset_df.index.isin(idx_list), 'dataset'] = dataset
    
    # Use the remaining samples for training
    dset_df.loc[dset_df['dataset'].isnull(), 'dataset'] = 'train'
    # Rename the dataset column to be consistent with the object detection data frames
    dset_df = dset_df.rename(columns={'dataset': 'dset'})
    return dset_df

In [17]:
# Create the data splits
dset_df = val_test_split(data=df_filtered, 
                         label_col=label_col,
                         n_test_per_class=30,
                         n_val_per_class=30)

In [18]:
# Make sure that we have three non-overlapping data sets
train_set = set(dset_df.loc[dset_df['dset']=='train', file_col].values)
print(f'We have {len(train_set)} images in the train set.')

val_set = set(dset_df.loc[dset_df['dset']=='val', file_col].values)
print(f'We have {len(val_set)} images in the validation set.')

test_set = set(dset_df.loc[dset_df['dset']=='test', file_col].values)
print(f'We have {len(test_set)} images in the test set.')
print()

# Make sure that these data sets are distinct
print(train_set.intersection(val_set))
print(train_set.intersection(test_set))
print(val_set.intersection(test_set))

We have 7190 images in the train set.
We have 180 images in the validation set.
We have 180 images in the test set.

set()
set()
set()

In [19]:
# Save the data split
datasplit_file_name = f'{os.path.splitext(annotations_file_name)[0]}_dset.parquet'
datasplit_file = os.path.join(image_dir, datasplit_file_name)
if not os.path.exists(datasplit_file):
    dset_df.to_parquet(datasplit_file)
else:
    print(f'Dataset file exists: {datasplit_file}.\nSkipping to overwrite this.')
display(dset_df.head())

Dataset file exists: /app/data/computervision_data/dataset_dental_roboflow/cropped/annotations_cropped_dset.parquet.
Skipping to overwrite this.

,multi_file,file_name,width,height,area,label,bbox,pos,pos_bbox,dset
0,a0ab0bec5c.jpg,tooth_02_a0ab0bec5c.jpg,152,236,35872,tooth,None,[2],None,train
1,5c6869fdf0.jpg,amalgam_03_5c6869fdf0.jpg,427,265,113155,amalgam,"[182, 29, 119, 112]","[19, 20]","[[143, 20, 284, 245], [20, 33, 382, 232]]",train
2,96a9546c1e.jpg,caries_08_96a9546c1e.jpg,525,253,132825,caries,"[97, 97, 46, 32]","[19, 20]","[[129, 21, 396, 232], [20, 20, 256, 233]]",train
3,1e36413c9e.jpg,composite_05_1e36413c9e.jpg,535,241,128935,composite,"[67, 32, 169, 87]","[29, 30]","[[213, 44, 322, 197], [20, 20, 341, 221]]",train
4,872cd0d6f2.jpg,tooth_15_872cd0d6f2.jpg,213,181,38553,tooth,None,[15],None,train

In [20]:
# Show the data splits
for dset in ['train', 'val', 'test']:
    print(f'Images in {dset.upper()}:')
    df1 = dset_df.loc[dset_df['dset'] == dset]
    n_images = df1[[file_col, label_col]].\
    groupby(label_col).\
    nunique().\
    reset_index(drop=False).\
    rename(columns={file_col: 'n_images'}).\
    sort_values(by='n_images', ascending=False).\
    reset_index(drop=True)
    display(n_images)

Images in TRAIN:

          label  n_images
0         tooth      3902
1     composite      1426
2       amalgam       600
3      Calculus       567
4        caries       518
5  root filling       177

Images in VAL:

          label  n_images
0      Calculus        30
1       amalgam        30
2        caries        30
3     composite        30
4  root filling        30
5         tooth        30

Images in TEST:

          label  n_images
0      Calculus        30
1       amalgam        30
2        caries        30
3     composite        30
4  root filling        30
5         tooth        30